# perl_ignore_file_pattern=.*\.swp$|.*\.log|$.*\.swo|\#---$
# ---
src/bash/sca-pola/funcs/run-sbt.func.sh
src/bash/sca-pola/specs/run-sbt.spec.sh
src/bash/sca-pola/tests/run-sbt.test.sh
doc/txt/sca-pola/funcs/run-sbt.func.txt
doc/txt/sca-pola/helps/run-sbt.help.txt
doc/txt/sca-pola/specs/run-sbt.spec.txt
doc/txt/sca-pola/tests/run-sbt.test.txt
# ---
src/bash/sca-pola/tests/run-sca-pola-tests.lst
src/scala/sca-pola/build.sbt
src/scala/sca-pola/project/ProjDependencies.scala
src/scala/sca-pola/project/plugins.sbt
src/scala/conf/application.ini
cnf/sca-pola.dev.host-name.cnf
cnf/sca-pola.host-name.cnf
# ---
src/scala/sca-pola/src
src/scala/sca-pola/src/main
src/scala/sca-pola/src/main/resources
src/scala/sca-pola/src/main/scala
src/scala/sca-pola/src/main/scala/com
src/scala/sca-pola/src/main/scala/com/csitea
src/scala/sca-pola/src/main/scala/com/csitea/app
src/scala/sca-pola/src/main/scala/com/csitea/app/ctrl
src/scala/sca-pola/src/main/scala/com/csitea/app/ctrl/CtrlConfig.scala
src/scala/sca-pola/src/main/scala/com/csitea/app/ctrl/CtrlMain.scala
src/scala/sca-pola/src/main/scala/com/csitea/app/io
src/scala/sca-pola/src/main/scala/com/csitea/app/io/in
src/scala/sca-pola/src/main/scala/com/csitea/app/io/in/RdrConfig.scala
src/scala/sca-pola/src/main/scala/com/csitea/app/io/out
src/scala/sca-pola/src/main/scala/com/csitea/app/io/out/WrtConfig.scala
src/scala/sca-pola/src/main/scala/com/csitea/app/Main.scala
src/scala/sca-pola/src/main/scala/com/csitea/app/utils
src/scala/sca-pola/src/main/scala/com/csitea/app/utils/Initiator.scala
src/scala/sca-pola/src/main/scala/com/csitea/app/utils/TypeConverter.scala
src/scala/sca-pola/src/test
src/scala/sca-pola/src/test/scala
src/scala/sca-pola/src/test/scala/com
src/scala/sca-pola/src/test/scala/com/csitea
src/scala/sca-pola/src/test/scala/com/csitea/app
src/scala/sca-pola/src/test/scala/com/csitea/app/ctrl
src/scala/sca-pola/src/test/scala/com/csitea/app/ctrl/TestCtrlMain.scala
src/scala/sca-pola/src/test/scala/com/csitea/app/utils
src/scala/sca-pola/src/test/scala/com/csitea/app/utils/TestInitiator.scala
src/scala/sca-pola/src/test/scala/com/csitea/app/utils/TestLogging.scala
# --- 
src/bash/lib/.bash_funcs.host-name
# ---
src/bash/sca-pola/tests/sbt-test.test.sh
src/bash/sca-pola/specs/sbt-test.spec.sh
src/bash/sca-pola/helps/sbt-test.help.sh
src/bash/sca-pola/funcs/sbt-test.func.sh
doc/txt/sca-pola/tests/sbt-test.test.txt
doc/txt/sca-pola/specs/sbt-test.spec.txt
doc/txt/sca-pola/helps/sbt-test.help.txt
doc/txt/sca-pola/funcs/sbt-test.func.txt
# ---
src/bash/sca-pola/funcs/package-scala-app.func.sh
src/bash/sca-pola/tests/package-scala-app.test.sh
src/bash/sca-pola/helps/package-scala-app.help.sh
src/bash/sca-pola/specs/package-scala-app.spec.sh
doc/txt/sca-pola/specs/package-scala-app.spec.txt
doc/txt/sca-pola/tests/package-scala-app.test.txt
doc/txt/sca-pola/helps/package-scala-app.help.txt
doc/txt/sca-pola/funcs/package-scala-app.func.txt
# --- 
src/bash/sca-pola/bootstrap-sca-pola.sh
src/bash/sca-pola/sca-pola.sh
src/bash/sca-pola/test-sca-pola.sh
src/bash/sca-pola/tests/all-sca-pola-tests.lst
src/bash/sca-pola/tests/rem-sca-pola-actions.lst
src/bash/sca-pola/tests/new-sca-pola-tests.lst
# ---
doc/txt/sca-pola/funcs/clone-project.func.txt
doc/txt/sca-pola/helps/clone-project.help.txt
doc/txt/sca-pola/specs/clone-project.spec.txt
doc/txt/sca-pola/tests/clone-project.test.txt
src/bash/sca-pola/funcs/clone-project.func.sh
src/bash/sca-pola/helps/clone-project.help.sh
src/bash/sca-pola/specs/clone-project.spec.sh
src/bash/sca-pola/tests/clone-project.test.sh
# ---
cnf
cnf/hosts
cnf/hosts/host-name
cnf/readme.txt
# ---
README.md
# ---
.gitignore
# ---
src/bash/sca-pola/tests/rem-sca-pola-actions.lst
src/bash/sca-pola/tmp
src/bash/sca-pola/sca-pola.cnf
src/bash/sca-pola/sca-pola.host-name.cnf
src/bash/sca-pola/sca-pola.set-your-host.cnf
#---
src/bash/sca-pola/funcs/remove-package.func.sh
src/bash/sca-pola/helps/remove-package.help.sh
src/bash/sca-pola/specs/pckg/remove-package.spec.sh
src/bash/sca-pola/specs/remove-package.spec.sh
src/bash/sca-pola/tests/pckg/remove-package.test.sh
src/bash/sca-pola/tests/remove-package.test.sh
doc/txt/sca-pola/funcs/remove-package.func.txt
doc/txt/sca-pola/helps/pckg/remove-package.help.txt
doc/txt/sca-pola/specs/pckg/remove-package.spec.txt
doc/txt/sca-pola/specs/remove-package.spec.txt
doc/txt/sca-pola/tests/remove-package.test.txt
src/bash/sca-pola/funcs/pckg/remove-package.func.sh
#---
doc/txt/sca-pola/funcs/create-ctags.func.txt
doc/txt/sca-pola/helps/dev/create-ctags.help.txt
doc/txt/sca-pola/specs/create-ctags.spec.txt
doc/txt/sca-pola/specs/dev/create-ctags.spec.txt
doc/txt/sca-pola/tests/create-ctags.test.txt
src/bash/sca-pola/funcs/dev/create-ctags.func.sh
src/bash/sca-pola/helps/create-ctags.help.sh
src/bash/sca-pola/specs/create-ctags.spec.sh
#---
src/bash/sca-pola/funcs/dev/morph-dir.func.sh
src/bash/sca-pola/helps/dev/morph-dir.help.sh
src/bash/sca-pola/specs/dev/morph-dir.spec.sh
src/bash/sca-pola/tests/dev/morph-dir.test.sh
doc/txt/sca-pola/funcs/morph-dir.func.txt
doc/txt/sca-pola/helps/dev/morph-dir.help.txt
doc/txt/sca-pola/specs/dev/morph-dir.spec.txt
doc/txt/sca-pola/tests/morph-dir.test.txt
#---
src/bash/sca-pola/specs/pckg/create-full-package.spec.sh
src/bash/sca-pola/helps/pckg/create-full-package.help.sh
src/bash/sca-pola/funcs/pckg/create-full-package.func.sh
src/bash/sca-pola/tests/pckg/create-full-package.test.sh
doc/txt/sca-pola/tests/pckg/create-full-package.test.txt
doc/txt/sca-pola/specs/pckg/create-full-package.spec.txt
doc/txt/sca-pola/helps/pckg/create-full-package.help.txt
doc/txt/sca-pola/funcs/pckg/create-full-package.func.txt
#---
src/bash/sca-pola/specs/pckg/create-full-7z-package.spec.sh
src/bash/sca-pola/helps/pckg/create-full-7z-package.help.sh
src/bash/sca-pola/funcs/pckg/create-full-7z-package.func.sh
src/bash/sca-pola/tests/pckg/create-full-7z-package.test.sh
doc/txt/sca-pola/tests/pckg/create-full-7z-package.test.txt
doc/txt/sca-pola/specs/pckg/create-full-7z-package.spec.txt
doc/txt/sca-pola/helps/pckg/create-full-7z-package.help.txt
doc/txt/sca-pola/funcs/pckg/create-full-7z-package.func.txt
#---
doc/txt/sca-pola/funcs/pckg/create-relative-7z-package.func.txt
doc/txt/sca-pola/helps/pckg/create-relative-7z-package.help.txt
doc/txt/sca-pola/specs/pckg/create-relative-7z-package.spec.txt
doc/txt/sca-pola/tests/pckg/create-relative-7z-package.test.txt
src/bash/sca-pola/funcs/pckg/create-relative-7z-package.func.sh
src/bash/sca-pola/helps/pckg/create-relative-7z-package.help.sh
src/bash/sca-pola/specs/pckg/create-relative-7z-package.spec.sh
src/bash/sca-pola/tests/pckg/create-relative-7z-package.test.sh
# ---
src/bash/sca-pola/tests/sys/backup-file.test.sh
src/bash/sca-pola/specs/sys/backup-file.spec.sh
src/bash/sca-pola/funcs/sys/backup-file.func.sh
doc/txt/sca-pola/tests/sys/backup-file.test.txt
doc/txt/sca-pola/specs/sys/backup-file.spec.txt
doc/txt/sca-pola/helps/sys/backup-file.help.txt
doc/txt/sca-pola/funcs/backup-file.func.txt
#---
doc/txt/sca-pola/specs/pckg/create-relative-package.spec.txt
doc/txt/sca-pola/tests/pckg/create-relative-package.test.txt
doc/txt/sca-pola/funcs/pckg/create-relative-package.func.txt
doc/txt/sca-pola/helps/pckg/create-relative-package.help.txt
src/bash/sca-pola/specs/pckg/create-relative-package.spec.sh
src/bash/sca-pola/helps/pckg/create-relative-package.help.sh
src/bash/sca-pola/funcs/pckg/create-relative-package.func.sh
src/bash/sca-pola/tests/pckg/create-relative-package.test.sh
met
met/.dev.sca-pola
met/.src.sca-pola
met/.tst.sca-pola
met/.prd.sca-pola
doc/txt/sca-pola/helps/dev/clone-to-app.help.txt
doc/txt/sca-pola/specs/dev/clone-to-app.spec.txt
src/bash/sca-pola/funcs/dev/clone-to-app.func.sh
src/bash/sca-pola/tests/dev/clone-to-app.test.sh
#---
doc/txt/sca-pola/funcs/change-version.func.txt
doc/txt/sca-pola/helps/change-version.help.txt
doc/txt/sca-pola/specs/change-version.spec.txt
doc/txt/sca-pola/tests/change-version.test.txt
src/bash/sca-pola/funcs/dev/change-version.func.sh
src/bash/sca-pola/helps/change-version.help.sh
src/bash/sca-pola/specs/change-version.spec.sh
src/bash/sca-pola/tests/change-version.test.sh
#---
doc/txt/sca-pola/specs/change-env-type.spec.txt
doc/txt/sca-pola/helps/change-env-type.help.txt
doc/txt/sca-pola/funcs/change-env-type.func.txt
doc/txt/sca-pola/tests/change-env-type.test.txt
src/bash/sca-pola/specs/change-env-type.spec.sh
src/bash/sca-pola/helps/change-env-type.help.sh
src/bash/sca-pola/funcs/change-env-type.func.sh
src/bash/sca-pola/tests/change-env-type.test.sh
#---
doc/txt/sca-pola/specs/remove-action-files.spec.txt
doc/txt/sca-pola/helps/remove-action-files.help.txt
doc/txt/sca-pola/funcs/remove-action-files.func.txt
doc/txt/sca-pola/tests/remove-action-files.test.txt
src/bash/sca-pola/specs/remove-action-files.spec.sh
src/bash/sca-pola/funcs/remove-action-files.func.sh
src/bash/sca-pola/helps/remove-action-files.help.sh
src/bash/sca-pola/tests/remove-action-files.test.sh
#---
doc/txt/sca-pola/funcs/print-help.func.txt
doc/txt/sca-pola/helps/man/print-help.help.txt
doc/txt/sca-pola/specs/man/print-help.spec.txt
doc/txt/sca-pola/tests/print-help.test.txt
src/bash/sca-pola/funcs/man/print-help.func.sh
src/bash/sca-pola/helps/print-help.help.sh
src/bash/sca-pola/specs/print-help.spec.sh
src/bash/sca-pola/tests/print-help.test.sh
#---
doc/txt/sca-pola/funcs/print-usage.func.txt
doc/txt/sca-pola/helps/man/print-usage.help.txt
doc/txt/sca-pola/specs/man/print-usage.spec.txt
doc/txt/sca-pola/tests/print-usage.test.txt
src/bash/sca-pola/funcs/man/print-usage.func.sh
src/bash/sca-pola/helps/print-usage.help.sh
src/bash/sca-pola/specs/print-usage.spec.sh
src/bash/sca-pola/tests/print-usage.test.sh
#---
doc/txt/sca-pola/funcs/generate-action-files.func.txt
doc/txt/sca-pola/helps/generate-action-files.help.txt
doc/txt/sca-pola/specs/generate-action-files.spec.txt
doc/txt/sca-pola/tests/generate-action-files.test.txt
src/bash/sca-pola/funcs/dev/generate-action-files.func.sh
src/bash/sca-pola/helps/generate-action-files.help.sh
src/bash/sca-pola/specs/generate-action-files.spec.sh
src/bash/sca-pola/tests/generate-action-files.test.sh
src/bash/sca-pola/funcs/%act%.%deliverable_type%.sh
doc/txt/sca-pola/tmpl/%act%.%deliverable_type%.txt
#---
doc/pdf
doc/md
#---
doc/txt/sca-pola/funcs/pckg/gmail-package.func.txt
doc/txt/sca-pola/helps/pckg/gmail-package.help.txt
doc/txt/sca-pola/specs/pckg/gmail-package.spec.txt
doc/txt/sca-pola/tests/pckg/gmail-package.test.txt
src/bash/sca-pola/helps/pckg/gmail-package.help.sh
src/bash/sca-pola/specs/pckg/gmail-package.spec.sh
src/bash/sca-pola/funcs/pckg/gmail-package.func.sh
src/bash/sca-pola/tests/pckg/gmail-package.test.sh
#--- 
LICENSE
lib/readme.txt
lib/bash/funcs/
lib/bash/funcs/parse-cnf-env-vars.sh
bin/readme.txt
dat/readme.txt
cnf/readme.txt
src/readme.txt
#---
doc/txt/sca-pola/specs/log-test-run-entry.spec.txt
doc/txt/sca-pola/funcs/log-test-run-entry.func.txt
doc/txt/sca-pola/tests/log-test-run-entry.test.txt
doc/txt/sca-pola/helps/log-test-run-entry.help.txt
src/bash/sca-pola/specs/log-test-run-entry.spec.sh
src/bash/sca-pola/funcs/log-test-run-entry.func.sh
src/bash/sca-pola/tests/log-test-run-entry.test.sh
src/bash/sca-pola/helps/log-test-run-entry.help.sh
dat/tests/1
doc/xls
doc/pdf
doc/pdf/README.pdf
doc/md
#---
doc/txt/sca-pola/helps/action-to-remove.help.txt
doc/txt/sca-pola/specs/action-to-remove.spec.txt
doc/txt/sca-pola/funcs/action-to-remove.func.txt
doc/txt/sca-pola/tests/action-to-remove.test.txt
src/bash/sca-pola/funcs/action-to-remove.func.sh
src/bash/sca-pola/helps/action-to-remove.help.sh
src/bash/sca-pola/helps/backup-file.help.sh
src/bash/sca-pola/specs/action-to-remove.spec.sh
doc/txt/sca-pola/funcs/clone-to-app.func.txt
doc/txt/sca-pola/tests/clone-to-app.test.txt
src/bash/sca-pola/helps/clone-to-app.help.sh
src/bash/sca-pola/specs/clone-to-app.spec.sh
src/bash/sca-pola/tests/action-to-remove.test.sh
src/bash/sca-pola/tests/create-ctags.test.sh
src/bash/sca-pola/specs/remove-package-files.spec.sh
src/bash/sca-pola/funcs/remove-package-files.func.sh
src/bash/sca-pola/tests/remove-package-files.test.sh
src/bash/sca-pola/helps/remove-package-files.help.sh
doc/txt/sca-pola/tests/remove-package-files.test.txt
doc/txt/sca-pola/specs/remove-package-files.spec.txt
doc/txt/sca-pola/helps/remove-package-files.help.txt
doc/txt/sca-pola/funcs/remove-package-files.func.txt
# --- 
tags
# ---
src/bash/sca-pola/funcs/gmail-txt-issues.func.sh
src/bash/sca-pola/tests/gmail-txt-issues.test.sh
src/bash/sca-pola/specs/gmail-txt-issues.spec.sh
src/bash/sca-pola/helps/gmail-txt-issues.help.sh
doc/txt/sca-pola/tests/gmail-txt-issues.test.txt
doc/txt/sca-pola/specs/gmail-txt-issues.spec.txt
doc/txt/sca-pola/helps/gmail-txt-issues.help.txt
doc/txt/sca-pola/funcs/gmail-txt-issues.func.txt
doc/pdf/
## --- 
doc/txt/sca-pola/helps/sbt-clean-compile.help.txt
doc/txt/sca-pola/tests/sbt-clean-compile.test.txt
doc/txt/sca-pola/funcs/sbt-clean-compile.func.txt
src/bash/sca-pola/helps/sbt-clean-compile.help.sh
# --- 
src/bash/sca-pola/tests/sbt-compile.test.sh
src/bash/sca-pola/funcs/sbt-compile.func.sh
doc/txt/sca-pola/funcs/sbt-compile.func.txt
doc/txt/sca-pola/tests/sbt-compile.test.txt
doc/txt/sca-pola/helps/sbt-compile.help.txt
src/bash/sca-pola/helps/sbt-compile.help.sh
# ---
src/bash/sca-pola/tests/sbt-compile-verbose.test.sh
doc/txt/sca-pola/funcs/sbt-compile-verbose.func.txt
src/bash/sca-pola/helps/sbt-compile-verbose.help.sh
doc/txt/sca-pola/helps/sbt-compile-verbose.help.txt
doc/txt/sca-pola/tests/sbt-compile-verbose.test.txt
# ---
src/bash/sca-pola/funcs/sbt-clean-compile.func.sh
src/bash/sca-pola/tests/sbt-clean-compile.test.sh
# ---
src/bash/sca-pola/funcs/scala/sbt-compile-verbose.func.sh
# ---
